export const BALL_PHYSICS = {
  radius: 7,
  artTextureSize: 32,
  contactRadius: 13,
  pickupRadius: 15,
  groundFrictionPerFrame: 0.984,
  wallRestitution: 0.74,
  maxWallReboundSpeed: 9.8,
  verticalGravityPerFrame: 0.20,
  verticalBounce: 0.22,
  minBounceVelocity: 0.9,
  maxVisualHeight: 50,
  maxHeightScaleBonus: 0.48,
  spinDecayPerFrame: 0.988,
  rollingSpinPerSpeed: 0.045,
  maxSpinPerFrame: 0.28,
  magnusForcePerSpin: 0.055,
  // Speed multiplied by (1 - |spin| * this factor) when kicked with spin
  spinSpeedCostFactor: 3.5,
} as const;
