const COUNTRY_CODES: Record<string, string> = {
  Afghanistan: 'af',
  Albania: 'al',
  Algeria: 'dz',
  Andorra: 'ad',
  Angola: 'ao',
  'Antigua and Barbuda': 'ag',
  Argentina: 'ar',
  Armenia: 'am',
  Australia: 'au',
  Austria: 'at',
  Azerbaijan: 'az',
  Bangladesh: 'bd',
  Barbados: 'bb',
  Belarus: 'by',
  Belgium: 'be',
  Benin: 'bj',
  Bermuda: 'bm',
  Bolivia: 'bo',
  'Bosnia and Herzegovina': 'ba',
  Brazil: 'br',
  Bulgaria: 'bg',
  'Burkina Faso': 'bf',
  Burundi: 'bi',
  Cameroon: 'cm',
  Canada: 'ca',
  'Cape Verde Islands': 'cv',
  'Central African Republic': 'cf',
  Chad: 'td',
  Chile: 'cl',
  'China PR': 'cn',
  'Chinese Taipei': 'tw',
  Colombia: 'co',
  Comoros: 'km',
  Congo: 'cg',
  'Congo DR': 'cd',
  'Costa Rica': 'cr',
  "Côte d'Ivoire": 'ci',
  Croatia: 'hr',
  Cuba: 'cu',
  Curacao: 'cw',
  Curaçao: 'cw',
  Cyprus: 'cy',
  'Czech Republic': 'cz',
  Czechia: 'cz',
  Denmark: 'dk',
  'Dominican Republic': 'do',
  Ecuador: 'ec',
  Egypt: 'eg',
  'El Salvador': 'sv',
  England: 'gb-eng',
  'Equatorial Guinea': 'gq',
  Estonia: 'ee',
  'Faroe Islands': 'fo',
  Finland: 'fi',
  France: 'fr',
  Gabon: 'ga',
  Gambia: 'gm',
  Georgia: 'ge',
  Germany: 'de',
  Ghana: 'gh',
  Gibraltar: 'gi',
  Greece: 'gr',
  Grenada: 'gd',
  Guatemala: 'gt',
  Guinea: 'gn',
  'Guinea-Bissau': 'gw',
  Guyana: 'gy',
  Haiti: 'ht',
  Holland: 'nl',
  Honduras: 'hn',
  'Hong Kong': 'hk',
  Hungary: 'hu',
  Iceland: 'is',
  India: 'in',
  Indonesia: 'id',
  Iran: 'ir',
  Iraq: 'iq',
  Ireland: 'ie',
  Israel: 'il',
  Italy: 'it',
  Jamaica: 'jm',
  Japan: 'jp',
  Jordan: 'jo',
  Kenya: 'ke',
  Korea: 'kr',
  'Korea Republic': 'kr',
  Kosovo: 'xk',
  Latvia: 'lv',
  Lebanon: 'lb',
  Liberia: 'lr',
  Libya: 'ly',
  Liechtenstein: 'li',
  Lithuania: 'lt',
  Luxembourg: 'lu',
  Madagascar: 'mg',
  Malawi: 'mw',
  Malaysia: 'my',
  Mali: 'ml',
  Malta: 'mt',
  Mauritania: 'mr',
  Mexico: 'mx',
  Moldova: 'md',
  Montenegro: 'me',
  Montserrat: 'ms',
  Morocco: 'ma',
  Mozambique: 'mz',
  Namibia: 'na',
  Netherlands: 'nl',
  'New Zealand': 'nz',
  Niger: 'ne',
  Nigeria: 'ng',
  'North Macedonia': 'mk',
  'Northern Ireland': 'gb-nir',
  Norway: 'no',
  Pakistan: 'pk',
  Palestine: 'ps',
  Panama: 'pa',
  Paraguay: 'py',
  Peru: 'pe',
  Philippines: 'ph',
  Poland: 'pl',
  Portugal: 'pt',
  'Republic of Ireland': 'ie',
  Romania: 'ro',
  Russia: 'ru',
  Rwanda: 'rw',
  'Saudi Arabia': 'sa',
  Scotland: 'gb-sct',
  Senegal: 'sn',
  Serbia: 'rs',
  'Sierra Leone': 'sl',
  Slovakia: 'sk',
  Slovenia: 'si',
  Somalia: 'so',
  'South Africa': 'za',
  Spain: 'es',
  'Sri Lanka': 'lk',
  'St. Kitts and Nevis': 'kn',
  'St. Lucia': 'lc',
  Suriname: 'sr',
  Sweden: 'se',
  Switzerland: 'ch',
  Syria: 'sy',
  Tajikistan: 'tj',
  Tanzania: 'tz',
  Thailand: 'th',
  Togo: 'tg',
  'Trinidad and Tobago': 'tt',
  Tunisia: 'tn',
  Turkey: 'tr',
  Uganda: 'ug',
  Ukraine: 'ua',
  'United Arab Emirates': 'ae',
  'United States': 'us',
  USA: 'us',
  Uruguay: 'uy',
  Uzbekistan: 'uz',
  Vanuatu: 'vu',
  Venezuela: 've',
  Wales: 'gb-wls',
  Zambia: 'zm',
  Zimbabwe: 'zw',
};

export function nationalityFlagCode(nationality: string): string {
  return COUNTRY_CODES[nationality] ?? '';
}
